default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/rachao_development.sqlite3

test:
  <<: *default
  database: db/rachao_test.sqlite3

production:
  <<: *default
  database: db/rachao_production.sqlite3
