name: Ruby

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.2'

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Set up database
      run: |
        RACK_ENV=test bundle exec rake db:create
        RACK_ENV=test bundle exec rake db:create_migration NAME=create_players
        RACK_ENV=test bundle exec rake db:migrate

    - name: Run tests
      run: RACK_ENV=test bundle exec rake spec:all